name: TurboAuth
version: 0.2.0
author: TurboAuth Team
website: https://github.com/turboauth/turboauth
main: com.turboauth.TurboAuth
api-version: 1.21
description: A lightweight, visually polished authentication plugin for offline/cracked servers

commands:
  turboauth:
    description: TurboAuth admin commands
    usage: /turboauth <reload|setspawn|setfallback|info|help>
    aliases: [ta]
    permission: turboauth.admin
    permission-message: '&c&l✗ &7You don''t have permission to use this command!'

  login:
    description: Login to the server
    usage: /login <password>
    aliases: [l]
    permission: turboauth.login
    permission-message: '&c&l✗ &7You don''t have permission to use this command!'

  register:
    description: Register a new account
    usage: /register <password> <password>
    aliases: [reg]
    permission: turboauth.register
    permission-message: '&c&l✗ &7You don''t have permission to use this command!'

permissions:
  turboauth.*:
    description: Gives access to all TurboAuth commands and features
    children:
      turboauth.admin: true
      turboauth.reload: true
      turboauth.login: true
      turboauth.register: true
    default: op

  turboauth.admin:
    description: Gives access to all TurboAuth admin commands
    children:
      turboauth.reload: true
    default: op

  turboauth.reload:
    description: Allows reloading TurboAuth configuration
    default: op

  turboauth.login:
    description: Allows login to the server
    default: true

  turboauth.register:
    description: Allows registration on the server
    default: true
